#!/bin/bash

# The MIT License (MIT)
#
#  Copyright (c) 2014 Carnegie Mellon University
#
#  Permission is hereby granted, free of charge, to any person obtaining a copy
#  of this software and associated documentation files (the "Software"), to deal
#  in the Software without restriction, including without limitation the rights
#  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#  copies of the Software, and to permit persons to whom the Software is
#  furnished to do so, subject to the following conditions:
#
#  The above copyright notice and this permission notice shall be included in
#  all copies or substantial portions of the Software.
#
#  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
#  THE SOFTWARE.

#
# @file   ShoppingNavigator
# @brief  Launch script for pedestrian navigation w/ IMUs and cameras
# @author M. George
#

if [ $# -ne 1 ]; then
echo "Please select a command."
else
 case "$1" in
        start)
        fabmap/bin/MOOSDB &
        sleep 1
        fabmap/bin/WordMaker WordMaker_IntelConfig.moos &
        sleep 2
        fabmap/bin/FabMapV2 FabMapV2_IntelConfig.moos &
        sleep 2
        echo "Starting ImageServer"
        # Argument is directory containing map.csv, don't forget the trailing slash /
        fusion/binary/ImageServer nrec-demo/ &
	sleep 2
        echo "Starting InertialTracker"
        fusion/binary/InertialTracker config.xml &
        ;;
        stop)
                kill -9 `ps -A | grep "MOOSDB" | awk '{print $1}'`
                kill -9 `ps -A | grep "WordMaker" | awk '{print $1}'`
                kill -9 `ps -A | grep "FabMapV2" | awk '{print $1}'`
                kill -9 `ps -A | grep "ImageServer" | awk '{print $1}'`
                kill -9 `ps -A | grep "InertialTracker" | awk '{print $1}'`
        ;;
        *)
                echo "$1 command is not available"
        ;;
 esac
fi
